### ISSUE TITLE
Mod no longer working

### ISSUE THREAD

**Issue by LordVGames** [Moffein/GiantParticleFix#1]
Used to work, but now particles are giant on parents after they teleport with the mod installed. Not sure when the mod broke.

https://github.com/Moffein/GiantParticleFix/assets/51967559/afd76579-fa34-4565-bc43-ad9dffdc12f0

**Comment by Moffein** [comment]
Seems like this was an oversight in the code. Nuxlar's GiantParticleFix fixes this bug, so I'd recommend swapping to that.
https://thunderstore.io/package/Nuxlar/DotParticleFix/
